---
- job:
    name: dlrn-api-functional-centos-7
    parent: dlrn-api-functional
    nodeset: centos-7-pod

- job:
    name: dlrn-api-functional-centos-8
    parent: dlrn-api-functional
    nodeset: centos-8-cloud

- project:
    name: dlrnapi_client
    check:
      jobs: &jobs
        - tox-pep8
        - tox-py27
        - tox-py36:
            nodeset: centos-8-cloud
        - tox-py37:
            nodeset: fedora-latest-pod
        - dlrn-api-functional-centos-7
        - dlrn-api-functional-centos-8
    gate:
      jobs: *jobs
    release:
      jobs:
        - upload-pypi
