---
- project:
    name: dlrnapi_client
    check:
      jobs:
        - tox-pep8
        - tox-py27
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - dlrn-api-functional
    gate:
      jobs:
        - tox-pep8
        - tox-py27
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - dlrn-api-functional
    release:
      jobs:
        - upload-pypi
